### ISSUE TITLE
Change workshop and conference date

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#107]
"A full day of PhoneGap, web, and mobile dev talks on Oct. 11th, plus an optional full day of workshops on Oct. 12th"

And change Oct 11 & 12 2017 • NYC to Oct 11 (conference) & 12 (workshops)

**Comment by GarthDB** [comment]
A couple more places to change the date:

- [ ] the [twitter card](/img/twitter-card-us2017sm.png)
- [ ] the [smaller logo](/img/pgd_logo_us-2017.svg)

**Comment by GarthDB** [comment]
It's fine to change these to just say oct 11, 12 or 11 & 12. Just so it's accurate; people can visit the site the get the break down of the days.
