### ISSUE TITLE
Tentative Agenda

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#11]
*Subject to change
- 8:30am-9:00am - Registration and breakfast
- 9:00am-9:15am – Michael Brooks... “PhoneGap kick off”
- 9:15am-9:50am – Eric Alli. .“Mind the Gap: Supercharge your PhoneGap workflow”
  Developing a complex and sustainable PhoneGap app can present many challenges. As your app grows, a seamless development workflow is crucial. Can you efficiently deploy and test in different environments? What are your pain points when implementing new functionality? How can you organize all the facets of your app with minimal effort?

Mind the gap focuses on some of the ways you can create a development workflow that automates these inefficiencies, boosts scalability and most of all, preserves developer sanity.
- 9:50am-10:10am – Martin Poschenrieder... “Automated App Testing: A pain or cure?”
  At testmunk we have been working with many popular apps by helping them ship better apps faster. We have automated testing for various Phonegap/Cordova apps (as well as others), allowing for quick detection of layout issues and crashes.

In this talk I'd like to touch on some of the testing challenges developers/QAs come across due to today’s large device and OS fragmentation, and how automated testing can ease some of these issues.

I will also show some examples of how developers can quickly set up their own automated tests and run them on a large set of devices 
- 10:10am-10:30am – Shawn Jansepar and Loki Meyburg (Mobify) “Finding the sweet spot - blending the best of native and web”
  Choose the best technology for the job. Too often projects begin as hybrid apps, but switch to native for performance reasons. But it’s almost never the case that all features of your app need to be fully native. Today, many apps such as Amazon, Basecamp, Yelp and more take a blended approach. We'll guide you through case studies of how we build high performance apps that blend the best of native and web and highlight lessons we've learned along the way.
- 10:30am-10:40am – BREAK
- 10:40am-11:00 – Mike Hartington (Ionic). . . . . “Ionic: Version 2 and Beyond”
  “Ionic 1.0 has enabled many web developers to become mobile app developers. With the arrival of Angular 2 and its changes, and with ES6 being finalized, development has been improved yet again. How will that impact Ionic? In this session, we’ll compare Ionic 1 and Ionic 2 and go over what we've learned, what improvements we're making to Ionic, and how easy it will be to develop apps with Ionic 2.”
- 11:00am-11:25am – Dean Haddock. . . . . . “The Story of an App: How StoryCorps Built and Launched the StoryCorps.me Beta Platform and What We've Learned So Far”
  Dean Haddock shares the story of the StoryCorps app, from early prototypes to the TED Prize and beyond.
- 11:25am-12:05pm – Alex Blom. . . . “PhoneGap Applications with Ember: Lessons learned”
  The benefits of hybrid applications are obvious (less code, simpler code, iterate faster). Developers often make quick pace, boot their app and then hit a wall trying to make it 'feel native'. 

This talk will discuss lessons learned & optimization techniques from having built many apps with Ember & phonegap. 

While this talk uses Ember & Ember packages, the tools and techniques discussed generically apply to any Phonegap application. 
12:05pm-12:25pm – Masahiro Tanaka (Asial Corporation)... “Using Monaca Cloud to enhance Cordova development”
- 12:25pm-1:15pm – LUNCH
- 1:15pm-1:35pm – Ryan J. Salva (Microsoft Visual Studio)
- 1:35pm-2:15pm – Jed Watson
- 2:15pm-2:35pm – Ray Camden. . . . . . . . . . . . “When the heck is 4/8/2016?”
  This talk will cover basic internationalization, globalization issues with Cordova apps. I'll talk about the Globalization plugin (and how to work around the async nature of the plugin), the Intl class, and other options. Also, I'll discuss why you should give a damn as a developer.
- 2:35pm-2:55pm – Rangle.io
- 2:55pm-3:25pm – Bruce Lefebvre. . . . . . . . . . . . “Making Enterprise Sh_t”
  Does the idea of writing enterprise software conjure up images of bland user interfaces, XML-based configuration, and IE8 compatibility? The folks on Adobe’s Experience Manager Apps team have been working hard at avoiding these stereotypes, while building a platform for delivering and managing mobile apps for enterprise customers. This talk will provide a glimpse into the following:
  What are the perks of including a content management system in my app dev arsenal?
  Which tools are available for me to take full advantage of Adobe’s Marketing Cloud solutions?
  As a developer, what open source goodness can I try out today?
- 3:25pm-3:45pm – Crosswalk
- 3:45pm-4:00pm – BREAK
- 4:00pm-4:30pm – Ryan Hanna. . .“Build and Market Your App: Small Team Success”
  This talk will provide the tools and methodologies to help any solo developer or small team build and then market their app to ensure it has the best chance for success.

We'll take a transparent look at the early beginnings of Sworkit to where it is now. From a single developer to a team of 10 employees, and from 10 downloads to 10 million. This talk will be a combination of the development and marketing lessons learned and implemented along the way. 
- 4:30pm-5:10pm – Renee Lance. . .”Generate for AEM and PhoneGap: Design Evolution 3.0 - D2W”
  Taking design to the digital environment has traditionally been time consuming, resource intensive and something designers and developers have been challenged with since the inception of designing for the web. So what if we had the ability to take design compositions from within Photoshop or Illustrator (or any other design tool if there really is any other) and directly turn them into and app, website or email marketing with a one button click?
  Something that seems too good to be true doesn’t it, well maybe not.  This talk will show new Adobe innovation still in the labs, which look at streamlining workflows and rapid prototyping for App creation with Adobe AEM and PhoneGap.
- 5:10pm-5:30pm – Shazron Abdullah... "Loading native code (plugins) dynamically for the enterprise"
  Hot-code reload for html/css/js is so 2015, everyone can do it. You probably thought you couldn't hot-reload plugin native code, well you were wrong! I'll show you how (and maybe bake a cake).
- 5:30pm 5:50pm – TJ VanToll (Telerik). . . . “Session: Cordova Plugin Roundup”
  In last few years Cordova plugins have become the cornerstone of many high-quality Cordova and PhoneGap applications. In just the last year, we at Telerik have grown our curated Cordova plugins marketplace from small handful of plugins to now 65 and counting. In this talk you’ll learn about the latest greatest in the Cordova plugin world, including plugins for the Apple Watch, Mapbox maps, and a whole lot more.
- 6:00pm-8:00pm – Pub mixer

**Comment by jenlgray** [comment]
Switch Eric Alli to the 9:15am-9:55am slot and put a TBD from 4:15-4:55

**Comment by GarthDB** [comment]
@jenlgray you can always edit the comment so we have one master copy.
Also if you are editing a closed issue, go ahead and reopen it.
