### ISSUE TITLE
Add agenda

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#120]
9:00am-9:30am - Registration and breakfast
9:30am-9:45am – ... PhoneGap kick off
9:45am-10:30am – Kerri Shotts . . . . . . . . “Modern JavaScript and PhoneGap”
JavaScript is changing with new versions of the standard now releasing every year, and lots of proposals being considered for inclusion. Most mobile devices can only support this new world with the help of automation, module loaders and bundlers, and transpilers… but if all of those words sound a little scary, don’t worry — it’s easy to build a workflow that integrates modern JavaScript and PhoneGap together, and in this session we’ll show you how!

10:30am-10:50am – Mike Hartington (Ionic) . . . . “Stencil.js and the future of components”
Have you ever found an awesome component online, but couldn't use it because it's written for a different framework? For too long now, frameworks have gotten in the way of developers sharing code that they've written. With different APIs to work with, developers would have to rewrite a component multiple times to be able to work with React, Angular, Vue, or even Ember. Enter Web Components. Built on open web standards, Web Components provide a way for creating reusable components that can work within every framework, and even outside of them. Find out what Ionic’s been experimenting with and see why Web Components are the way of the future.

10:50am-11:10am – BREAK
 
11:10am-11:30am – Nicole Alexander
11:30am-12:10pm – Greg Avola

12:10pm-1:10pm – LUNCH
 
1:10pm-1:50pm – Alex Blom . . . . . . .“Performant Animations for Hybrid Apps”
Adding animations to web and hybrid apps can be challenging. Aside from choosing technique, you are often left with jank and less than desirable performance - sometimes even after following best practices for animations.
This talk will cover:
1: What are my choices when animating?;
2: What are the tradeoffs / how do I decide?;
3: What are the common pitfalls?;
4: How do I debug performance problems?;
5: Getting a smooth animation.

1:50pm-2:10pm – Masa Tanaka

2:10pm-2:30pm - Jesse MacFadyen

2:30pm-2:50pm - Greg Bulmash . . . .“Rolling Your Own Multi-Platform Voice Assistant”
Voice is the new IU of choice, and while most mobile platforms have some voice functionality built in, cloud-based voice APIs are making it possible to create a unified voice-powered experience that follows you from mobile to desktop to… Walk through building a voice-powered PhoneGap app on desktop and mobile, using Amazon’s Lex and Polly services from AWS to voice-enable your apps

2:50pm-3:10pm - BREAK
 
3:10pm-3:30pm - TBD
3:30pm-4:10pm - John Wargo
4:10pm-4:50pm - Henry Zhu
4:50pm-5:10pm - Closing remarks

**Comment by GarthDB** [comment]
@rajarju I assigned this to you, but would you prefer I take it?

**Comment by rajarju** [comment]
@GarthDB 
No, I will work this :)
Thanks
