### ISSUE TITLE
Add description to Nicole's talk

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#127]
Talk description: Consumers are generating massive amounts of data through their mobile devices; data that can help businesses’ better aggregate consumer offerings, increase interaction and engagement while allowing businesses to tap into a trillion dollar mobile economy. However, trust and lack of transparency has proven to be key barriers. In this discussion we will look at how these opportunities can be leveraged by understanding consumers motivations.

**Comment by GarthDB** [comment]
@rajarju just closed it.
