### ISSUE TITLE
PG Day EU speakers

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#13]
1. Remy Sharp - https://remysharp.com/about#bio
2. Masahiro Tanaka, CEO of Asial Corporation

Masa is the CEO of Asial Corporation, the company behind Japan's #1 hybrid app development tools, Monaca and Onsen UI. He started his company as a pioneer in web and mobile communities in Japan, writing numerous PHP books and initiating Cordova meetups. Masa still maintains a leadership role within mobile and IoT communities in Japan and overseas as a hybrid app development vanguard and framework trendsetter.

![massie bio](https://cloud.githubusercontent.com/assets/9487317/11311335/6826277e-8f8c-11e5-978f-190ee5c4cd5b.jpeg)
1. Dean Haddock (same from US site)
2. Simon MacDonald (same from US site)
3. Holly Schinsky (same from US site)
4. Jesse MacFadyen (same from US site)
5. Anis Kadri (same from US site)
6. Steve Gill (same from US site)
7. Shaz Abdullah (same from US site)
8. Sani Yusuf - Sani runs a startup called HAIBRID that uses cross-platform mobile development techniques to create innovative ​mobile ​ solutions. Sani also co-manages the Ionic UK community in UK and has had stints with companies like Microsoft, Huddlebuy & Anritsu in the past. ​ @saniyusuf​ 

![unknown](https://cloud.githubusercontent.com/assets/9487317/13438797/cd9d1638-dfa7-11e5-9fde-fe39be44afd7.jpeg)
1. Kerri Shotts - Kerri Shotts is an IT consultant specializing in mobile hybrid application development. She has used PhoneGap/Cordova for several years while developing enterprise apps for her clients. She is the author of five books about PhoneGap. She serves as a moderator on the PhoneGap Google Group. Kerri is also a photographer and loves caffeine, art, music, and Minecraft.
   Twitter: @photokandy
   Website: http://www.photokandy.com, http://kerrishotts.github.io

![portrait](https://cloud.githubusercontent.com/assets/9487317/13442661/916888ba-dfba-11e5-80e0-6fd854de229b.jpg)
1. Niels Leenheer - Niels is a founder of Salonhub and creates web applications for a living. He has been using PhoneGap professionally for the last five years. In his free time he runs one of the largest Open Device Labs in the world, created the HTML5test.com website and has recently given a number of talks about Smart TV and game console browsers. He loves to research obscure browsers and submit bug reports.

![unknown-1](https://cloud.githubusercontent.com/assets/9487317/13462822/8b52ee16-e046-11e5-9ecd-484bbfa902bd.jpeg)
1. Ryan Willoughby - Software Engineer, Adobe
   Ryan works on PhoneGap Build and Cordova. He recently watched The Mist and threw a can of Old Milwaukee at the television in frustration. Not the bourbon sour though.

![unknown-2](https://cloud.githubusercontent.com/assets/9487317/13477188/5e7ca674-e088-11e5-9c24-08a3da0a1503.jpeg)
1. Brett Rudd - waiting on info
2. Steve Gill - (comment below)

**Comment by stevengill** [comment]
Steve Gill

![newheadshot](https://cloud.githubusercontent.com/assets/169536/13468705/cc693380-e058-11e5-9d42-cfb2980fbab1.jpg)

Originally from Vancouver but currently living in San Francisco, Steve has been part of the PhoneGap team since 2009! He currently works on the tooling for Cordova and helps with releases. Outside of hacking, he loves hockey, biking, yoga and traveling!

Title: Software Engineer, Adobe

**Comment by jenlgray** [comment]
And remove the "interested speaking?" call for speakers link
