### ISSUE TITLE
More updates

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#130]
1. Add Henry Zhu as a speaker and add his talk to agenda
Headshot: 
![6lc-7xqg_400x400](https://user-images.githubusercontent.com/9487317/30757029-5e8f6530-9f8a-11e7-820c-c10e267ceba2.jpg)
Bio: Henry is a maintainer on Babel and works at Adobe on the Behance team in NYC
Talk title: The Future of Babel with babel-preset-env 

2. Add Lars bio
Bio: As a principal at Adobe, Lars’ work spans engineering, product management and marketing. His focus is on combining AI, Serverless computing, and open APIs to enable the next generation of digital experiences. Originally from Berlin, Germany, you find Lars these days mostly in airport security lines, sushi bars, and on Slack.

3. Add talk title and description to Masa's speaker profile and agenda
Talk title: Flawless development with Vue, Monaca and Onsen UI ♨️
Talk description: While Cordova can be used with all major frameworks like Angular and React, using with Vue has a great advantage especially for building handy apps.

This session will describe how to develop an app with Vue and Onsen UI, fully made by Web Components, using toolchain provided by Monaca development platform.

4. Add Brian Leroux as speaker
Headshot: 
![brian_leroux_final009](https://user-images.githubusercontent.com/9487317/30759217-a3c65070-9f92-11e7-8b62-2d1782694a03.jpg)

Bio: Brian declined to write a bio because talking in the third person weirds me out man.

**Comment by jenlgray** [comment]
Update on these additions @GarthDB @rajarju ?

**Comment by GarthDB** [comment]
I'll get them published today.
