### ISSUE TITLE
Add Mobify's workshop content

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#20]
Mobify Workshop: "Build the Amazon App"

A workshop on quickly building a hybrid app with feature parity to Amazon's app with a mix of native and web interfaces

In this workshop we will guide you through building a commerce-enabled app with feature parity to the Amazon iOS app using a combination of web and native components using Astro, our latest SDK built on top of Cordova.

**Comment by GarthDB** [comment]
@jenlgray Right now all the session and workshop descriptions are shown on the speaker page, do you have speakers for the remaining sessions (including this one)?
