### ISSUE TITLE
Workshop speakers

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#25]
1. (Mobify) Build the Amazon App - Shawn Jansepar and Loki Meyburg
2. (Telerik) Cordova plugins in action - TJ VanToll and Brian Rinaldi
3. No speaker or description from Rangle.io yet
4. No speaker or description for Redhat yet
5. Crosswalk workshop speaker - Alexis Menard - Software Engineer, Intel
   Bio: Alexis Menard is a software engineer working at Intel in Oregon as part of the Open Source Technology Center. Here his main focus is on the ever evolving Web Platform, which includes work on W3C standards as well as Blink/Chromium. In the latter projects, he serves as both developer and code reviewer. Alexis is also working on Crosswalk, an HTML5 runtime/webview for Android and Windows where he does a bit of everything. Prior to Intel, Alexis worked on QtWebKit and WebKit itself at the Brazilian Nokia research center known as INdT. Before moving to Brazil, Alexis worked out of Norway, mostly on the Qt framework as a part of Nokia (former Trolltech). He is also a former KDE contributor where he contributed mostly to Plasma, the desktop shell of KDE.

![alexis-menard](https://cloud.githubusercontent.com/assets/9487317/12152138/0965dd2a-b470-11e5-91f9-05b8f1a69e02.jpg)
1. Crosswalk workshop - Title:  "Hands on: Create advanced apps with the Crosswalk runtime”
   Abstract: Join Crosswalk architect, Alexis Menard, in a hands-on lab where you will discover how to leverage the power of Crosswalk in your web and hybrid applications and take advantage of the latest web innovations across Android, iOS, and Windows.
2. Quickly install and build with Crosswalk and Cordova.
               - Create an app for Android and Windows using Crosswalk-app-tools
               - Learn advanced features in your application can run across platforms
3. Crosswalk session speaker - Bob Spencer - Software Architect, Intel
   Bio:  Bob Spencer is a software architect in Intel's Open Source Technology Center where for the past decade his work has been centered on open source developer tools and SDKs.  He is the community manager on the Crosswalk Project team.  In his free time he will be biking, backpacking, or hanging with his family.

![bob-spencer](https://cloud.githubusercontent.com/assets/9487317/12152151/428e523a-b470-11e5-9fab-91780837509a.jpg)
1. Crosswalk session - "The Crosswalk Advantage – a powerful runtime for your Cordova Apps"
   Abstract:  Discover how to add advanced capabilities to your PhoneGap applications with very little effort.  The Crosswalk runtime gives your application the ability to use the newest, just-released features on all platforms with predictable behavior.
2. Asial workshop is being given by Masa Tanaka

**Comment by GarthDB** [comment]
@jenlgray you're the best.
