### ISSUE TITLE
Workshop info

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#39]
We're changing things up this year for PhoneGap Day EUers and having 2 separate tracks of workshops with a "choose your own adventure" theme. We'll have great content running all day in two different rooms so you can pick and choose what topics you'd like to get some hands-on experience with. The PhoneGap team and other community experts will be running workshops on everything from plugin development to embeddable webviews.

**Important: workshop location is different than the conference venue**

Pakhuis De Zwijger
Piet Heinkade 179
1019 HC Amsterdam

https://dezwijger.nl/

photo of the venue: 
![unknown](https://cloud.githubusercontent.com/assets/9487317/13462792/65418ade-e046-11e5-9482-445f870fdb07.jpeg)

Public transport information:

“To reach the workshop venue, go to Central Station and take tram 26. It’s located very close to the second stop; you can see it from the tram."

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/13594513/46002fce-e4c2-11e5-9a84-f55be699c4df.png)
