### ISSUE TITLE
Add Canonical speaker, workshop info

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#60]
1. David Barth - Engineering Manager, Product Strategy, Canonical
   Bio: David heads up the Webapps Team at Canonical, the makers of Ubuntu. David and his team’s involvement in Ubuntu app development is centered on the integration of web technologies into the core of the Ubuntu platform. This includes the development of the Oxide project, a modern webview optimized to run on Ubuntu, the Ubuntu Cordova port, and more generally JS frameworks related to developing apps and "scopes" on Ubuntu.

![unknown-1](https://cloud.githubusercontent.com/assets/9487317/14795236/c97a0742-0ae4-11e6-962d-0a793418ba38.png)
1. Workshop info for Canonical (3:45pm-4:45pm timeslot)
   Title: Developing Cordova apps on Ubuntu devices 

Description: We'll walk you through the basics of getting a development environment ready for Cordova on Ubuntu, talk about specific aspects of the Ubuntu application model and security, and run a couple of demos to illustrate the capabilities of the platform and of the Ubuntu Oxide webview. With Ubuntu spanning across Desktop, mobile and IOT with converged laptop / tablet device, this will be the opportunity to see how Cordova apps can literally stretch across form factors.

**Comment by GarthDB** [comment]
This is the info currently on the website. Not sure why it was opened up again.
