### ISSUE TITLE
Make it easier/faster to get to Schedule section

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-day#65]
Right now, it requires a buttload of scrolling to get to the Schedule section of the site, which is particularly nasty on mobile. I'd suggest a menu to be able to jump directly to the section of interest.

Current sections that could be included: The Lowdown, Speakers, Schedule, Workshops, Venue, Sponsors, Code of Conduct

**Comment by GarthDB** [comment]
I could add a menu, but it'll take some work. As far as the order of importance I'm thinking:
- schedule
- workshops
- speakers
- venue
- sponsors
- code of conduct.

I don't think we actually need to include the lowdown or even the registration section for the week of the event. Should we keep the speakers section? I'm planning on returning it back to the current state afterwards.

What do you think @jahoni & @jenlgray?

**Comment by jahoni** [comment]
if menu is too much work to add, okay.

re-order of list looks good to me - though I also wonder if having location/venue information higher up would be better. related: are there actually more details coming soon related to the venue? might it make sense to specify/clarify where the conference vs. workshops are happening?

I don't have a preference on removing lowdown/registration info.

**Comment by GarthDB** [comment]
The site is now ready for pgday with the changes. http://pgday.phonegap.com/eu2016/
