### ISSUE TITLE
Sponsor logo layout improvement

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-day#67]
Personal preference, but I feel like the sponsor logos look pretty jammed together.

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/15301028/86a07136-1b60-11e6-909b-08c1f38a0a64.png)

I'd suggest reducing the visual entropy by making all the logos a single colour kinda like:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/15301099/de05c728-1b60-11e6-87e6-87a285aefb65.png)

**Comment by GarthDB** [comment]
I don't think we could set them to be single color without getting permission. @jenlgray do you think they'd be alright with it?

**Comment by jenlgray** [comment]
Good question. I think it'll be okay.

**Comment by GarthDB** [comment]
ok, it looks much better, so I'll go ahead. I'll keep the color versions in the folder just in case someone gets upset.
