### ISSUE TITLE
PhoneGap Day 2017 site

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap-day#69]
## Main site

http://pgday.phonegap.com/

PhoneGap Day US 2017 - Fall 2017 (details to come)
PhoneGap Day EU 2017 - May 18-19 2017, Amsterdam

## PhoneGap Day EU page

1. Change date on main banner
2. Second tile - same text, change the date to May 18-19, ticket pricing ( Early Bird conference €120 + VAT, Early Bird conference + workshops €245 + VAT), Get Tickets link - https://webconferences.paydro.com/phonegap-day-eu-2017
3. Schedule - Announcing soon!
4. Get some 1:1 time with our PhoneGap experts ahead of the conference. Join our workshop day on Thursday, May 18. We'll have 2 workshop tracks on May 18th with great content running all day. More details to be announced soon, but we'll have workshops on things like progressive web apps, offline capabilities, security, and virtual reality. You won't want to miss these! Note: the workshop venue is different than the conference venue. More information coming soon!
5. Venue - same conference venue, Het Compagnietheater
6. Speakers (from the last PGDay US and EU sites)
- Simon MacDonald
- Holly Schinsky
- Jesse MacFadyen
- Kerri Shotts
- Ryan Hanna
- Sani Yusuf
7. Sponsors - What would PhoneGap Day be without our amazing partners? Interested in getting involved? Email Jen Gray at jgray@adobe.com for sponsorship opportunities
8. Same Code of Conduct

## Sign up form

Can we implement a sign up form for announcements on the main page? Just a "sign up for PhoneGap Day updates"

**Comment by GarthDB** [comment]
I believe it's all published and working.

Could you take a look @jenlgray? http://pgday.phonegap.com/

**Comment by shazron** [comment]
```
PhoneGap Day
US 2017
More details to come. Sign up to recieve updates.
```
spelling:  recieve should be `receive`

**Comment by GarthDB** [comment]
@shazron hey thanks - fixing now.

**Comment by jenlgray** [comment]
This is the workshop venue info:

Spaces Herengracht
Herengracht 124-128,
1015 BT Amsterdam
https://goo.gl/maps/uvby2U7nLpT2
