### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap-day#7]
- [x] [Mobify](http://www.mobify.com/style-guide/brand-assets)
- [x] Ionic
- [x] Mobify
- [x] Rangle.io
- [x] Onsen UI
- [x] Monaca
- [x] Visual Studio

**Comment by jenlgray** [comment]
![onsen ui logo](https://cloud.githubusercontent.com/assets/9487317/11311354/9405109e-8f8c-11e5-934f-52022778a30f.png)

![monaca logo](https://cloud.githubusercontent.com/assets/9487317/11311355/96a55728-8f8c-11e5-9654-517555f16ea8.png)

![imgres](https://cloud.githubusercontent.com/assets/9487317/11311375/ba999e3c-8f8c-11e5-818f-363f9ca79c34.png)
